### ISSUE TITLE
Enlaces a las páginas de los usuarios en la tabla "Results of the game"

### ISSUE THREAD

**Issue by dfjhh** [jantoniomartin/machiavelli#13]
Al finalizar una partida, la página de dicha partida tiene una tabla con los resultados llamada "Results of the game "XXXX"". En ella aparecen los nombres de los usuarios.

Se podría hacer que dichos nombres fueran enlaces a sus páginas personales facilitando la visita a los perfiles de aquellos con los que has competido.

**Comment by jantoniomartin** [comment]
Acabo de modificarlo. Gracias por la sugerencia.
